# Generated by Django 2.2.9 on 2022-10-28 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20221027_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='выберете к какой группе принаджежит пост', null=True, on_delete=django.db.models.deletion.PROTECT, to='posts.Group', verbose_name='Группы'),
        ),
    ]
