# Generated by Django 2.2.9 on 2022-10-31 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20221028_0746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='выберете к какой группе принадлежит пост', null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Group', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='введите содержание поста', verbose_name='текст поста'),
        ),
    ]
