# Generated by Django 2.2.9 on 2022-11-01 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20221031_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='выберете к какой группе принадлежит пост', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postsgroup', to='posts.Group', verbose_name='Группы'),
        ),
    ]
